version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./backend:/app
      - mounts_data:/app/mounts.json

volumes:
  mounts_data: